app = "quran-radio-bot"
primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_kind = ""
  [services.ports]
    force_https = true
    handlers = ["http"]
    port = 80
    [services.ports.http_options]
    [services.ports.tls_options]
  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"